#!/usr/bin/env python3
"""Monte Carlo diagnostics for the random-LCM coprime-density CLT."""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from exact_variance import primes_up_to


def prime_factor_masks(M: int) -> tuple[np.ndarray, np.ndarray]:
    """Return a factor-incidence matrix for integers 2..M and log weights."""
    primes = np.asarray(primes_up_to(M), dtype=np.int64)
    masks = np.zeros((M - 1, len(primes)), dtype=bool)
    values = np.arange(2, M + 1, dtype=np.int64)
    for idx, p in enumerate(primes):
        masks[:, idx] = values % p == 0
    log_weights = np.log1p(-1.0 / primes.astype(np.float64))
    return masks, log_weights


def coprime_density_samples(M: int, k: int, N: int, seed: int) -> np.ndarray:
    """Generate N samples of phi(L_k)/L_k without constructing the LCM."""
    rng = np.random.default_rng(seed)
    masks, log_weights = prime_factor_masks(M)
    output = np.empty(N, dtype=np.float64)
    for row in range(N):
        draws = rng.integers(0, M - 1, size=k)
        # Repeated draws do not change which primes have appeared.
        observed = masks[np.unique(draws)].any(axis=0)
        output[row] = math.exp(float(log_weights[observed].sum()))
    return output


def standardized_moments(values: np.ndarray) -> tuple[np.ndarray, float, float]:
    """Standardize by sample mean and sample SD; return skewness and excess kurtosis."""
    mean = float(values.mean())
    sd = float(values.std(ddof=1))
    z = (values - mean) / sd
    # Fisher-Pearson moment diagnostics, matching the descriptive convention used
    # in the manuscript.  These are not bias-corrected estimators.
    skewness = float(np.mean(z**3))
    excess_kurtosis = float(np.mean(z**4) - 3.0)
    return z, skewness, excess_kurtosis


def normal_density(x: np.ndarray) -> np.ndarray:
    return np.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


def run_experiment(
    output_figure: Path,
    output_csv: Path,
    seed: int = 2026,
) -> None:
    cases = [(100, 100, 3000), (300, 300, 3000), (1000, 1000, 1000)]
    output_figure.parent.mkdir(parents=True, exist_ok=True)
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    diagnostics: list[tuple[int, int, int, int, float, float, float, float]] = []
    fig, axes = plt.subplots(1, 3, figsize=(12.5, 3.7), constrained_layout=True)
    x = np.linspace(-4.0, 4.0, 600)

    # Each panel is generated by a fresh NumPy default_rng with the declared seed.

    for ax, (M, k, N) in zip(axes, cases):
        case_seed = seed
        values = coprime_density_samples(M, k, N, case_seed)
        z, skewness, excess_kurtosis = standardized_moments(values)
        diagnostics.append(
            (
                M,
                k,
                N,
                case_seed,
                float(values.mean()),
                float(values.std(ddof=1)),
                skewness,
                excess_kurtosis,
            )
        )
        ax.hist(z, bins=35, range=(-4, 4), density=True, alpha=0.65, edgecolor="white")
        ax.plot(x, normal_density(x), linewidth=1.8, label=r"$\mathcal{N}(0,1)$")
        ax.set_xlim(-4, 4)
        ax.set_ylim(bottom=0)
        ax.set_title(
            f"M = {M}, k = {k}\n"
            f"skew = {skewness:.2f}, excess kurt = {excess_kurtosis:.2f}",
            fontsize=9,
        )
        ax.set_xlabel(r"$(\varphi(L_k)/L_k-\hat\rho_k)/\hat\sigma_k$")
        ax.legend(loc="upper left", fontsize=8)
    axes[0].set_ylabel("density")
    fig.savefig(output_figure, dpi=220)
    plt.close(fig)

    with output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "M",
                "k",
                "N",
                "case_seed",
                "sample_mean",
                "sample_sd_ddof1",
                "moment_skewness",
                "moment_excess_kurtosis",
            ]
        )
        writer.writerows(diagnostics)

    print(f"Wrote {output_figure}")
    print(f"Wrote {output_csv}")
    for row in diagnostics:
        print(
            f"M={row[0]} N={row[2]} seed={row[3]} "
            f"skew={row[6]:.4f} excess_kurtosis={row[7]:.4f}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument(
        "--figure", type=Path, default=Path("paper/figures/fig_clt_distribution.png")
    )
    parser.add_argument(
        "--output", type=Path, default=Path("data/simulation_diagnostics.csv")
    )
    args = parser.parse_args()
    run_experiment(args.figure, args.output, seed=args.seed)


if __name__ == "__main__":
    main()
